#!/bin/bash

help() {
  echo "Usage:"
  echo "  zgeth exec"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  ensure_config

  zmicro plugin run compose exec $GETH_SERVICE_NAME:geth $@
}

run() {
  core $@
}

run $@
