#!/bin/bash

help() {
  echo "Usage:"
  echo "  zgeth start"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  ensure_config

  zmicro plugin run compose start $PLUGIN_GETH_NAME

  # init user
  # @TODO
  # zmicro plugin run compose exec $PLUGIN_GETH_NAME:geth delete_admin admin >>/dev/null 2>&1
  # #
  # zmicro plugin run compose exec $PLUGIN_GETH_NAME:geth create_admin admin admin >>/dev/null 2>&1

  log_success "启动成功"
}

run() {
  core $@
}

run $@
