version: '3.7'

services:
  geth:
    restart: always
    image: ethereum/client-go:${GETH_SERVICE_VERSION}
    ports:
      - ${GETH_SERVICE_PORT}:3334
    environment:
      TZ: Asia/Shanghai
    entrypoint: geth --mainnet --syncmode "light" --ws --ws.addr 0.0.0.0 --ws.port 3334 --datadir /data
    volumes:
      - ${PLUGIN_GETH_DATA}:/data

networks:
  default:
    external: true
    name: compose-ingress